### PR TITLE
[DML] Convert NCHW{n, c, h, w} to NHWC{n, h, w, c} in order t…

### PR DESCRIPTION
**Pull request by fujunwei**
…o reshape NCHW{n, c, h, w} to NCHW{n, 1, c * h * w / x, x} in Fully Connected Operation.

### CODE REVIEW

**Comment by fujunwei** [comment]
It's to fix https://github.com/intel/webml-polyfill/issues/872.

**Comment by huningxin** [comment]
Thanks @fujunwei . Did you happen to run the regression test?

**Comment by fujunwei** [comment]
PR Submission Proposal:
    ➤   Win-WebNN-Fast-MKLDNN: OK
    ➤   Win-WebNN-Sustained-clDNN: OK
    ➤   Win-WebNN-Sustained-DML: OK
PR Submission Message:
Total Test Cases: 2151
Pass to Fail: 0
Fail to Pass: 0

**Comment by huningxin** [comment]
Great. Looks good. Thanks.

**Pull request merged**
