### PR TITLE
Support MobileNet Model

### PR DESCRIPTION
**Pull request by fujunwei**

### CODE REVIEW

**Comment by fujunwei** [comment]
MobileNet need take ~80ms predicted time that need to be investigated.

PR Submission Proposal:
    ➤   Win-WebNN-Fast-MKLDNN: OK
    ➤   Win-WebNN-Sustained-clDNN: OK
    ➤   Win-WebNN-Sustained-DML: OK

286 test cases has passed.

**Comment by fujunwei** [comment]
The sample of [DirectMLSuperResolution ](https://github.com/microsoft/DirectML-Samples/tree/master/DirectMLSuperResolution) take ~11s inference time.

**Comment by fujunwei** [comment]
Baseline Information:
Chromium version: b5692cd
Webml-polyfill version: 853173e
PR Submission Proposal:
    ➤   Win-WebNN-Sustained-DML: OK
PR Submission Message:
Total Test Cases: 714
Pass to Fail: 0
Fail to Pass: 74

**Comment by huningxin** [comment]
Looks good. Thanks.

**Pull request merged**
