### PR TITLE
[IE] support AVERAGE_POOL_2D and MAX_POOL_2D

### PR DESCRIPTION
**Pull request by huningxin**
fix https://github.com/intel/webml-polyfill/issues/699

### CODE REVIEW

**Comment by huningxin** [comment]
Test results:
https://brucedai.github.io/nt/test/max_pool_2d.html?backend=mkldnn
MKLDNN: passes: 5 failures: 1 duration: 0.09s
IE/MKLDNN: passes: 5 failures: 1 duration: 0.10s

https://brucedai.github.io/nt/test/avg_pool_2d.html?backend=mkldnn
MKLDNN: passes: 6 failures: 1 duration: 0.20s
IE/MKLDNN: passes: 6 failures: 1 duration: 0.21s

**Comment by huningxin** [comment]
@fujunwei , PTAL. Thanks!

**Comment by fujunwei** [comment]
LGTM.

**Comment by huningxin** [comment]
Thanks!

**Pull request merged**
