### PR TITLE
[Linux] Enable clDNN backend on Linux

### PR DESCRIPTION
**Pull request by fujunwei**
Which is based on ningxin 's windows implementation.

Fix https://github.com/intel/webml-polyfill/issues/179.

### CODE REVIEW

**Comment by fujunwei** [comment]
@huningxin PTAL, thanks.

**Comment by huningxin** [comment]
Thanks. Looks good. Please remove the unused Linux implementation in this PR.

**Comment by fujunwei** [comment]
Thanks, done.

**Comment by huningxin** [comment]
Looks good. Thanks!

**Pull request merged**
