### PR TITLE
Break function execution when DOM exception is thrown

### PR DESCRIPTION
**Pull request by sunlin-link**

### CODE REVIEW

**Comment by sunlin-link** [comment]
Fixes following issues:
https://github.com/intel/webml-polyfill/issues/77

**Comment by sunlin-link** [comment]
@huningxin @gyagp Please help to review

**Comment by huningxin** [comment]
Looks good. Thanks for the fix!

**Comment by huningxin** [comment]
@gyagp is out of office and may not have time to review this project. 

@fujunwei , please help take a look. Thanks!

**Comment by fujunwei** [comment]
LGTM.

**Pull request merged**
