### PR TITLE
MKLDNN pool

### PR DESCRIPTION
**Pull request by huningxin**

### CODE REVIEW

**Comment by huningxin** [comment]
PR Submission Checking Summary
Baseline Information:
Chromium version: 8b58220
Webml-polyfill version: c261a0a
PR Submission Proposal:
    ➤   Linux-clDNN: OK
    ➤   Linux-MKLDNN: OK
    ➤   Linux-WASM: OK
    ➤   Linux-WebGL: OK
PR Submission Message:
Total Test Cases: 2600
Pass to Fail: 0
Fail to Pass: 42


Feature | TestCase | Baseline | Linux-MKLDNN
-- | -- | -- | --
CTS | CTS-check result for Avg pool float example/1 | Fail | Pass
CTS | CTS-check result for Avg pool float relu example/1 | Fail | Pass
CTS | CTS-check result for Avg pool float relu6 example/1 | Fail | Pass
CTS | CTS-check result for Avg pool float example/2 | Fail | Pass
CTS | CTS-check result for Avg pool float example/3 | Fail | Pass
CTS | CTS-check result for Avg pool float example/4 | Fail | Pass
CTS | CTS-check result for Max pool float example/1 | Fail | Pass
CTS | CTS-check result for Max pool float relu example/1 | Fail | Pass
CTS | CTS-check result for Max pool float relu6 example/1 | Fail | Pass
CTS | CTS-check result for Max pool float example/2 | Fail | Pass
CTS | CTS-check result for Max pool float example/3 | Fail | Pass

**Comment by huningxin** [comment]
@fujunwei , PTAL. Thanks!

**Comment by fujunwei** [comment]
LGTM, thanks.

**Comment by huningxin** [comment]
Thanks for reviewing!

**Pull request merged**
