### PR TITLE
[IE] enable VPU

### PR DESCRIPTION
**Pull request by huningxin**
fix https://github.com/intel/webml-polyfill/issues/706 https://github.com/intel/webml-polyfill/issues/734

### CODE REVIEW

**Comment by huningxin** [comment]
PR Submission Checking Summary
Baseline Information:
Chromium version: ef9d267
Webml-polyfill version: 475aff9
PR Submission Proposal:
    ➤   Linux-clDNN: OK
    ➤   Linux-IE-MKLDNN: Please improve the code
    ➤   Linux-MKLDNN: OK
PR Submission Message:
Total Test Cases: 2142
Pass to Fail: 1
Fail to Pass: 12

The Pass to fail case is

Feature | TestCase | Baseline | Linux-IE-MKLDNN
-- | -- | -- | --
Unit Test/Execution Test | setInput API-check "setInput" is a function | Pass | Fail


Actually it's a test case issue: https://github.com/intel/webml-polyfill/issues/747

**Comment by huningxin** [comment]
@fujunwei , PTAL. Thanks!

**Comment by fujunwei** [comment]
LGTM.

**Comment by huningxin** [comment]
Thanks!

**Pull request merged**
